<?xml version="1.0" encoding="utf-8"?><Database Name="PhanPhoiThuoc" Class="dbDrugStoreManagerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-O2938GT\SQLEXPRESS;Initial Catalog=PhanPhoiThuoc;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PhanPhoiThuocConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHI_TIET_DON_DAT_HANG" Member="CHI_TIET_DON_DAT_HANGs">
    <Type Name="CHI_TIET_DON_DAT_HANG">
      <Column Name="MaDDH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DVT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="SAN_PHAM_CHI_TIET_DON_DAT_HANG" Member="SAN_PHAM" ThisKey="MaSP" OtherKey="MaSP" Type="SAN_PHAM" IsForeignKey="true" />
      <Association Name="DON_DAT_HANG_CHI_TIET_DON_DAT_HANG" Member="DON_DAT_HANG" ThisKey="MaDDH" OtherKey="MaDDH" Type="DON_DAT_HANG" IsForeignKey="true" />
      <Association Name="DVT_CHI_TIET_DON_DAT_HANG" Member="DVT1" ThisKey="DVT" OtherKey="MaDVT" Type="DVT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SAN_PHAM" Member="SAN_PHAMs">
    <Type Name="SAN_PHAM">
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaLoaiSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DVT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongTon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Images" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="SAN_PHAM_CHI_TIET_DON_DAT_HANG" Member="CHI_TIET_DON_DAT_HANGs" ThisKey="MaSP" OtherKey="MaSP" Type="CHI_TIET_DON_DAT_HANG" />
      <Association Name="SAN_PHAM_CHI_TIET_PHIEU_GIAO_HANG" Member="CHI_TIET_PHIEU_GIAO_HANGs" ThisKey="MaSP" OtherKey="MaSP" Type="CHI_TIET_PHIEU_GIAO_HANG" />
      <Association Name="SAN_PHAM_CT_HOA_DON" Member="CT_HOA_DONs" ThisKey="MaSP" OtherKey="MaSP" Type="CT_HOA_DON" />
      <Association Name="DVT_SAN_PHAM" Member="DVT1" ThisKey="DVT" OtherKey="MaDVT" Type="DVT" IsForeignKey="true" />
      <Association Name="LOAI_SAN_PHAM_SAN_PHAM" Member="LOAI_SAN_PHAM" ThisKey="MaLoaiSP" OtherKey="MaLoaiSP" Type="LOAI_SAN_PHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHI_TIET_PHIEU_GIAO_HANG" Member="CHI_TIET_PHIEU_GIAO_HANGs">
    <Type Name="CHI_TIET_PHIEU_GIAO_HANG">
      <Column Name="MaPGH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DVT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="SAN_PHAM_CHI_TIET_PHIEU_GIAO_HANG" Member="SAN_PHAM" ThisKey="MaSP" OtherKey="MaSP" Type="SAN_PHAM" IsForeignKey="true" />
      <Association Name="DVT_CHI_TIET_PHIEU_GIAO_HANG" Member="DVT1" ThisKey="DVT" OtherKey="MaDVT" Type="DVT" IsForeignKey="true" />
      <Association Name="PHIEU_GIAO_HANG_CHI_TIET_PHIEU_GIAO_HANG" Member="PHIEU_GIAO_HANG" ThisKey="MaPGH" OtherKey="MaPGH" Type="PHIEU_GIAO_HANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_HOA_DON" Member="CT_HOA_DONs">
    <Type Name="CT_HOA_DON">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DVT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="SAN_PHAM_CT_HOA_DON" Member="SAN_PHAM" ThisKey="MaSP" OtherKey="MaSP" Type="SAN_PHAM" IsForeignKey="true" />
      <Association Name="DVT_CT_HOA_DON" Member="DVT1" ThisKey="DVT" OtherKey="MaDVT" Type="DVT" IsForeignKey="true" />
      <Association Name="HOA_DON_CT_HOA_DON" Member="HOA_DON" ThisKey="MaHD" OtherKey="MaHD" Type="HOA_DON" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DangNhap" Member="DangNhaps">
    <Type Name="DangNhap">
      <Column Name="id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PhanQuyen" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DON_DAT_HANG" Member="DON_DAT_HANGs">
    <Type Name="DON_DAT_HANG">
      <Column Name="MaDDH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayLapDon" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="DON_DAT_HANG_CHI_TIET_DON_DAT_HANG" Member="CHI_TIET_DON_DAT_HANGs" ThisKey="MaDDH" OtherKey="MaDDH" Type="CHI_TIET_DON_DAT_HANG" />
      <Association Name="DON_DAT_HANG_PHIEU_GIAO_HANG" Member="PHIEU_GIAO_HANGs" ThisKey="MaDDH" OtherKey="MaDDH" Type="PHIEU_GIAO_HANG" />
    </Type>
  </Table>
  <Table Name="dbo.DVT" Member="DVTs">
    <Type Name="DVT">
      <Column Name="MaDVT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDVT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DVT_CHI_TIET_DON_DAT_HANG" Member="CHI_TIET_DON_DAT_HANGs" ThisKey="MaDVT" OtherKey="DVT" Type="CHI_TIET_DON_DAT_HANG" />
      <Association Name="DVT_SAN_PHAM" Member="SAN_PHAMs" ThisKey="MaDVT" OtherKey="DVT" Type="SAN_PHAM" />
      <Association Name="DVT_CHI_TIET_PHIEU_GIAO_HANG" Member="CHI_TIET_PHIEU_GIAO_HANGs" ThisKey="MaDVT" OtherKey="DVT" Type="CHI_TIET_PHIEU_GIAO_HANG" />
      <Association Name="DVT_CT_HOA_DON" Member="CT_HOA_DONs" ThisKey="MaDVT" OtherKey="DVT" Type="CT_HOA_DON" />
    </Type>
  </Table>
  <Table Name="dbo.HOA_DON" Member="HOA_DONs">
    <Type Name="HOA_DON">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLapHD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HinhThucThanhToan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="HOA_DON_CT_HOA_DON" Member="CT_HOA_DONs" ThisKey="MaHD" OtherKey="MaHD" Type="CT_HOA_DON" />
      <Association Name="KHACH_HANG_HOA_DON" Member="KHACH_HANG" ThisKey="MaKH" OtherKey="MaKH" Type="KHACH_HANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACH_HANG" Member="KHACH_HANGs">
    <Type Name="KHACH_HANG">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDLogin" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="KHACH_HANG_HOA_DON" Member="HOA_DONs" ThisKey="MaKH" OtherKey="MaKH" Type="HOA_DON" />
    </Type>
  </Table>
  <Table Name="dbo.LOAI_NV" Member="LOAI_NVs">
    <Type Name="LOAI_NV">
      <Column Name="MaLoaiNV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoaiNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LOAI_NV_NHAN_VIEN" Member="NHAN_VIENs" ThisKey="MaLoaiNV" OtherKey="MaLoaiNV" Type="NHAN_VIEN" />
    </Type>
  </Table>
  <Table Name="dbo.LOAI_SAN_PHAM" Member="LOAI_SAN_PHAMs">
    <Type Name="LOAI_SAN_PHAM">
      <Column Name="MaLoaiSP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LOAI_SAN_PHAM_SAN_PHAM" Member="SAN_PHAMs" ThisKey="MaLoaiSP" OtherKey="MaLoaiSP" Type="SAN_PHAM" />
    </Type>
  </Table>
  <Table Name="dbo.NHAN_VIEN" Member="NHAN_VIENs">
    <Type Name="NHAN_VIEN">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaLoaiNV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NHAN_VIEN_PHIEU_GIAO_HANG" Member="PHIEU_GIAO_HANGs" ThisKey="MaNV" OtherKey="MaNV" Type="PHIEU_GIAO_HANG" />
      <Association Name="LOAI_NV_NHAN_VIEN" Member="LOAI_NV" ThisKey="MaLoaiNV" OtherKey="MaLoaiNV" Type="LOAI_NV" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEU_GIAO_HANG" Member="PHIEU_GIAO_HANGs">
    <Type Name="PHIEU_GIAO_HANG">
      <Column Name="MaPGH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDDH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="PHIEU_GIAO_HANG_CHI_TIET_PHIEU_GIAO_HANG" Member="CHI_TIET_PHIEU_GIAO_HANGs" ThisKey="MaPGH" OtherKey="MaPGH" Type="CHI_TIET_PHIEU_GIAO_HANG" />
      <Association Name="DON_DAT_HANG_PHIEU_GIAO_HANG" Member="DON_DAT_HANG" ThisKey="MaDDH" OtherKey="MaDDH" Type="DON_DAT_HANG" IsForeignKey="true" />
      <Association Name="NHAN_VIEN_PHIEU_GIAO_HANG" Member="NHAN_VIEN" ThisKey="MaNV" OtherKey="MaNV" Type="NHAN_VIEN" IsForeignKey="true" />
    </Type>
  </Table>
</Database>